name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install docker desktop
      run: |
        sudo ls
        echo "Downloading DMG."
        curl -Lo docker.dmg https://download.docker.com/mac/stable/28905/Docker.dmg
        echo "Extract DMG."
        hdiutil attach docker.dmg
        echo "Install Docker."
        echo "ls"
        sudo find / | grep Docker.app
    - name: docker version
      run: docker version
